"""Escalation reason code enum-like constants."""
from __future__ import annotations

LOW_INTENT_CONFIDENCE = "LOW_INTENT_CONFIDENCE"
NO_RELEVANT_HISTORY = "NO_RELEVANT_HISTORY"
UNSUPPORTED_INFORMATION = "UNSUPPORTED_INFORMATION"
SENSITIVE_ACCOUNT_ACTION = "SENSITIVE_ACCOUNT_ACTION"
CONFLICTING_HISTORY = "CONFLICTING_HISTORY"
UNKNOWN_INTENT = "UNKNOWN_INTENT"
REPEATED_FAILURE = "REPEATED_FAILURE"
HIGH_RISK_REQUEST = "HIGH_RISK_REQUEST"

ALL_REASON_CODES = [
    LOW_INTENT_CONFIDENCE,
    NO_RELEVANT_HISTORY,
    UNSUPPORTED_INFORMATION,
    SENSITIVE_ACCOUNT_ACTION,
    CONFLICTING_HISTORY,
    UNKNOWN_INTENT,
    REPEATED_FAILURE,
    HIGH_RISK_REQUEST,
]
